### ISSUE TITLE
Investigate if we need to set up context for this example

### ISSUE THREAD

**Issue by janedegtiareva** [near-examples/rust-counter#14]
A lot of simple contracts can pass unit tests without setting up context and testing_env.

For the sake of keeping examples simple, we may want to consider omitting these lines from test setup:

let context = get_context(vec![], false);
testing_env!(context);

(there are pros and cons to that: pros that there is less code clutter, cons that it makes it harder to add on and make more complex code out of the example without figuring this out)

**Comment by mikedotexe** [comment]
I've commented it out in the three tests and they all fail.
